#!/usr/bin/env python3
import os
import subprocess

print("\033[1;32m\n\n\nGitHub Co-pilot >_\033[0m\n")
print("\033[1;32m     created by Mohammed Magdy :)\033[0m \n\n\n")
################ Adding permissions ###################
cwd = os.getcwd()
files = os.listdir(cwd)
ignore_list=['~','README.md']
for file in files:
	if file not in ignore_list:
		os.chmod(file,0o777)
	else:
		continue

################ Git Scripts ###################
# Set the remote and branch
#origin = 'origin'#str(input("input the origin (defualt origin): "))
branch = 'master'#str(input("input the branch you want to push to (defualt master): "))
commit_massage = 'Hello C-lang '#str(input("input the commit massage you want to commit: "))

#run the git and the push command
subprocess.run(['git','add','.'])
subprocess.run(['git','commit','-m',commit_massage])
subprocess.run(['git','push'])
